### PR TITLE
feat(podcasts): adding a new feature area for podcasts

### PR DESCRIPTION
**Pull request by runrog**

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by runrog** [comment]
run ci

**Comment by runrog** [comment]
[run cl]

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Review by WidgetsBurritos — CHANGES_REQUESTED** [review]
This looks fine, but will you remove the dist from the PR now? The deployment process will rebuild that.

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Review by WidgetsBurritos — APPROVED** [review]
👍 LGTM

**Comment by WidgetsBurritos** [comment]
[run ci]

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Review by WidgetsBurritos — CHANGES_REQUESTED** [review]
So I know it's slightly out of scope for this ticket, but one other minor fix: 
```(@text minute listen)```

^ can we ensure that text is getting translated?
https://github.com/rackerlabs/solve/pull/48/commits/14a1136e0df0efd9d7da213ae09bb5445ff9d24a#diff-9fc21165842d97c3a33633eb13608fa7R72

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by runrog** [comment]
@WidgetsBurritos translation is done

**Review by WidgetsBurritos — APPROVED** [review]
👍 on 5f639fd90b5bd3e1df5e3ebaf59f5e4e385a4bf9

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5609-podcast-box.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Pull request merged**
