### PR TITLE
fix(logger): assign bug in ie for logger

### PR DESCRIPTION
**Pull request by runrog**
looks like the next version of vue-logger addresses this very issue
https://github.com/justinkames/vuejs-logger/commit/9ecff59145562274a5ab33901ea5b4c8b0c2d653

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by runrog** [comment]
Taken from the Babel docs in adding the pollyfill

Screen Shot 2019-12-16 at 1 55 23 PM

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Review by WidgetsBurritos — CHANGES_REQUESTED** [review]
Don't include the dist in the PRs anymore.  This will get automatically built when we do a version bump

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Comment by runrog** [comment]
[run ci]

**Comment by WidgetsBurritos** [comment]
[run ci]

**Comment by WidgetsBurritos** [comment]
Preview URL: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5247-broken-ie11.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Review by WidgetsBurritos — APPROVED** [review]
👍 LGTM

**Pull request merged**
