### PR TITLE
chore(npm): Revert file

### PR DESCRIPTION
**Pull request by WidgetsBurritos**
Revert the ignore scripts change

### CODE REVIEW

**Comment by WidgetsBurritos** [comment]
[run ci]

**Comment by WidgetsBurritos** [comment]
[run ci]

**Comment by WidgetsBurritos** [comment]
Preview URL: http://revert-scripts.solve.dev.website.rackspace.com/solve

Login Url: http://revert-scripts.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

**Review by xinbin — APPROVED** [review]
+9000

**Pull request merged**
